dataset: StanfordCars
dataset_args: {split: test}

encoder: convnet4_21
encoder_args: {}

relation_net: relation_net
relation_net_args: {}

load: /baseline_model_path/max-va.pth
load_relation: /baseline_model_path/max-va.pth

