# dataset: CUB_crop/StanfordCars/StanfordDogs/Aircraft/nabirds/tiered-imagenet
dataset: StanfordCars
dataset_args: {split: test}

encoder: convnet4_21
encoder_args: {}

relation_net: relation_net
relation_net_args: {input_size: [64, 21, 21]}

trans_net: conv_helix_transformer
trans_net_args: {dim: 64, s1_emb_dim: 64, s1_emb_kernel: 3, s1_emb_stride: 1,
                   s1_proj_kernel: 3, s1_kv_proj_stride: 1, s1_heads: 2, s1_dim_head: 64,
                   s1_depth: 1, s1_mlp_mult: 4, dropout: 0.}

load: /model_path/max-va.pth
load_relation: /model_path/max-va.pth
load_trans: /model_path/max-va.pth

