train_dataset: CUB_crop
train_dataset_args: {split: train, augment: new_crop}
tval_dataset: CUB_crop
tval_dataset_args: {split: test}
val_dataset: CUB_crop
val_dataset_args: {split: val}


encoder: convnet4_21
encoder_args: {}

relation_net: relation_net
relation_net_args: {}

load_encoder: /remote-home/source/69/yuanjiakang/FSFG_Baseline_icip_51/save/classifier_new_gap_tiered-imagenet_resnet12/epoch-100.pth

n_way: 5
n_shot: 5
n_query: 15
train_batches: 200
ep_per_batch: 4
max_epoch: 130

optimizer: sgd
optimizer_args: {lr: 0.01, milestones: [70, 110]}


optimizer_rn: adam
optimizer_rn_args: {lr: 0.001, milestones: [70, 110]}

visualize_datasets: True

