# dataset(augment): CUB_crop(new_crop)/StanfordCars(color)/StanfordDogs(color)
#                   Aircraft(color)/nabirds(color)/tiered-imagenet(new_crop)
train_dataset: StanfordCars
train_dataset_args: {split: train, augment: color}
tval_dataset: StanfordCars
tval_dataset_args: {split: test}
val_dataset: StanfordCars
val_dataset_args: {split: val}

encoder: convnet4_21
encoder_args: {}

relation_net: relation_net
# convnet4_21: input_size=[64, 21, 21]
# resnet12: input_size=[512, 10, 10]
relation_net_args: {input_size: [64, 21, 21]}

# trans_net: conv_helix_transformer/linear_helix_transformer
trans_net: conv_helix_transformer
trans_net_args:   {dim: 64, emb_dim: 64, emb_kernel: 3, emb_stride: 1,
                   proj_kernel: 3, kv_proj_stride: 1, heads: 2, dim_head: 64,
                   depth: 1, mlp_mult: 4, dropout: 0.}

# pretrained backbone
# save_path/epoch-100.pth
load_encoder: /pretrain_model_path/epoch-100.pth

# 5shot setting
#n_way: 5
#n_shot: 5
#n_query: 15
#n_train_way: 5
#n_train_shot: 5
#n_train_query: 15
#train_batches: 250
#ep_per_batch: 2
#max_epoch: 150
#
#optimizer: adam
#optimizer_args: {lr: 0.001,  milestones: [80, 120]}
#
#optimizer_rn: adam
#optimizer_rn_args: {lr: 0.001, milestones: [80, 120]}
#
#
#optimizer_trans: adam
#optimizer_trans_args: {lr: 0.001, milestones: [80, 120]}

# 1shot setting
n_way: 5
n_shot: 1
n_query: 15
n_train_way: 5
n_train_shot: 1
n_train_query: 15
train_batches: 250
ep_per_batch: 4
max_epoch: 130

optimizer: adam
optimizer_args: {lr: 0.001,  milestones: [70, 110]}

optimizer_rn: adam
optimizer_rn_args: {lr: 0.001, milestones: [70, 110]}

optimizer_trans: adam
optimizer_trans_args: {lr: 0.001, milestones: [70, 110]}

visualize_datasets: True