train_dataset: StanfordCars
train_dataset_args: {split: train, augment: color}
tval_dataset: StanfordCars
tval_dataset_args: {split: test}
val_dataset: StanfordCars
val_dataset_args: {split: val}


encoder: convnet4_21
encoder_args: {}

relation_net: relation_net
relation_net_args: {}

load_encoder: /pretrain_model_path/epoch-100.pth

n_way: 5
n_shot: 1
n_query: 15
train_batches: 200
ep_per_batch: 4
max_epoch: 130

optimizer: sgd
optimizer_args: {lr: 0.01, milestones: [70, 110]}


optimizer_rn: adam
optimizer_rn_args: {lr: 0.001, milestones: [70, 110]}

visualize_datasets: True

